db_to_excel_tables = {
	"Sample": ["Summary", "1.MetaData"],
    "Tissue": "2.Tissue",
    "DNA_Extraction": "3.DNAExtractions",
    "RNA_Extraction": "3.RNAExtractions",
    "Illumina_Library": "4.Illumina",
    "PacBio_Library": "4.PacBio",
    "HiC_Lysate": "4.HiCLysate",
    "HiC_Library": "4.HiCLibrary",
    "ONT_Library": "4.ONT",
    "RNA_Library": "4.RNAIllumina",
    "Sequencing": "5.Sequencing"
}

excel_to_db_tables = {
	"Summary": "Sample",
    "1.MetaData": "Sample",
    "2.Tissue": "Tissue",
    "3.DNAExtractions": "DNA_Extraction",
    "3.RNAExtractions": "RNA_Extraction",
    "4.Illumina": "Illumina_Library",
    "4.PacBio": "PacBio_Library",
    "4.HiCLysate": "HiC_Lysate",
    "4.HiCLibrary": "HiC_Library",
    "4.ONT": "ONT_Library",
    "4.RNAIllumina": "RNA_Library",
    "5.Sequencing": "Sequencing"
}

db_to_excel_cols = {
	"Sample": {
        "og_id": ["Specimen ID", "OGID"],
		"field_id": "Field Identifier",
		"nominal_species_id": "Nominal Species ID",
		"common_name": "Common name/s",
		"collector": "Collector",
		"contact": "Contact",
		"date_collected": "Date_Collected",
		"sex": "Sex",
		"weight": "Weight (g)",
		"lengthTL_and_lengthFL": "Length (TL or FL mm)",
		"country": "Country",
		"state": "State",
		"location": "Location",
		"latitude_collection": "Latitude_Collection",
		"longitude_collection": "Longitude_Collection",
		"depth_collection": "Depth_Collection (m)",
		"collection_method": "Collection_Method",
		"preservation_method": "Preservation_Method",
		"sample_condition": "Sample_Condition",
		"photo_voucher": "Photo_Voucher",
		"photo_id": "Photo_Voucher_Accession_Details",
		"specimen_voucher": "Specimen_Voucher",
		"voucher_id": "Specimen_Voucher_Accession_details",
		"comments": "Comments",
		"priority": "Priority",
		"tissues": "Tissues",
		"extracted": "Extracted",
		"extraction_queue": "DNA Extraction Status",
		"ilmn": "ilmn",
		"il_status": "Illumina Status",
		"hifi": "hifi",
		"pb_status": "PacBio Status",
		"hic": "hic",
		"hic_status": "HiC Status",
		"nano": "nano",
		"ont_num": "NanoPore Status",
		"rna": "rna",
		"rna_status": "RNA Extraction Status",
		"ilrna": "ilrna",
		"ilrna_status": "Illumina RNA Status"
	},
	"Tissue": {
		"tissue_id": "Sample ID",
		"og_id": "Specimen ID",
		"field_id": "Field Identifier",
		"alt_id": "Alt ID",
		"tissue": "Tissue",
		"extracted": "Extracted",
		"freezer": "Freezer",
		"shelf": "Shelf",
		"rack": "Rack",
		"level": "Level",
		"box": "Box Label",
		"comment": "Comment"
	},
	"RNA_Extraction": {
		"rna_id": "Tube ID",
		"tissue_id": "Sample ID",
		"ext_num": "#",
		"status": "Status",
		"extraction_method": "Extraction Method",
		"extraction_date": "Extraction Date",
		"extraction_batch_id": "Extraction Batch ID",
		"final_buffer": "Final Buffer",
		"volume": "Volume (uL)",
		"qubit_conc": "Qubit Conc. (ng/uL)",
		"nano_drop_conc": "NanoDrop Conc. (ng/uL)",
		"ratio_260_280": "260/280",
		"ratio_260_230": "260/230",
		"total_yield": "Total Yield (ng)",
		"tapestation_id": "TapeStation Run ID",
		"rna_dv200": "RNA DV200",
		"rin": "RIN",
		"extraction_qc": "Pass / Fail QC",
		"comment": "Comment",
		"rna_freezer": "RNA Archives Freezer",
		"rna_shelf": "Shelf",
		"rna_rack": "Rack",
		"rna_level": "Level",
		"rna_box": "Box Label",
		"rna_notes": "Notes"
	},
	"DNA_Extraction": {
		"dna_id": "Tube ID",
		"tissue_id": "Sample ID",
		"ext_num": "#",
		"status": "Status",
		"extraction_method": "Extraction Method",
		"extraction_date": "Extraction Date",
		"extraction_batch_id": "Extraction Batch ID",
		"final_buffer": "Final Buffer",
		"volume": "Volume (uL)",
		"qubit_conc": "Qubit Conc. (ng/uL)",
		"nano_drop_conc": "NanoDrop Conc. (ng/uL)",
		"ratio_260_280": "260/280",
		"ratio_260_230": "260/230",
		"ratioqubit_nanodrop": "Qubit:NanoDrop Ratio",
		"total_yield": "Total Yield (ng)",
		"gdna_femtol_id": "gDNA Femto ID",
		"av_size": "Average size (bp)",
		"extraction_qc": "Pass / Fail QC",
		"comment": "Comment",
		"dna_Freezer": "DNA Archives Freezer",
		"dna_Shelf": "Shelf",
		"dna_Rack": "Rack",
		"dna_Level": "Level",
		"dna_Box": "Box Label",
		"dna_Notes": "Notes"
	},
	"HiC_Lysate": {
		"lysate_id": "Lysate Tube ID",
		"tissue_id": "Sample ID",
		"lysate_num": "#",
		"lysate_status": "Status",
		"lysate_prep_date": "Lysate Prep Date",
		"lysate_batch_id": "Lysate Batch ID",
		"lysate_conc": "Lysate Conc. (ng/uL)",
		"total_lysate": "Total Lysate (ng)",
		"lysate_cde": "CDE (%)",
		"lysate_comments": "Comments"
	},
	"RNA_Library": {
		"rna_library_tube_id": "Library Tube ID",
		"rna_id": "RNA Tube ID",
		"rna_num": "#",
		"rna_status": "Status",
		"library_method": "Library Prep Method",
		"library_date": "Library Prep Date",
		"library_id": "Library Batch ID",
		"library_size": "cDNA Library Size (bp)",
		"perc_product": "% Product",
		"library_qubit_conc": "Library Qubit Conc. (ng/ul)",
		"library_molarity": "Library Molarity (nM)",
		"index_set": "IDT® for Illumina® DNA/RNA UD Indexes Set",
		"index_well": "Illumina Index Adaptor Well",
		"index_inx": "Illumina Contatenate Index",
		"kinnex_primers": "PacBo Kinnex Barcoded Primers",
		"kinnex_barcode": "PacBio Kinnex Library Barcode",
		"il_comments": "Comments"
	},
	"Illumina_Library": {
		"illumina_library_tube_id": "Library Tube ID",
		"dna_id": "DNA Tube ID",
		"ilmn_num": "#",
		"ilmn_status": "Status",
		"library_method": "Library Prep Method",
		"library_date": "Library Prep Date",
		"library_id": "Library Batch ID",
		"index_set": "IDT® for Illumina® DNA/RNA UD Indexes Set",
		"index_well": "Index Adaptor Well",
		"index_idx": "Concatenate Index",
		"library_qubit_conc": "Library Qubit Conc. (ng/ul)",
		"il_comments": "Comments"
	},
	"ONT_Library": {
		"ont_library_tube_id": "Library Tube ID",
		"dna_id": "DNA Tube ID",
		"ont_num": "#",
		"ont_status": "Status",
		"library_date": "Library Prep Date",
		"library_id": "Library Batch ID",
		"library_method": "Library Prep Method",
		"library_type": "Library Type",
		"est_loading_size": "Estimated Loading size (bp)",
		"ont_comments": "Comments"
	},
	"PacBio_Library": {
		"pacbio_library_tube_id": "Library Tube ID",
		"dna_id": "DNA Tube ID",
		"pacb_num": "#",
		"pacb_status": "Status",
		"library_method": "Library Prep Method",
		"library_date": "Library Prep Date",
		"library_id": "Library Batch ID",
		"dna_treatment": "DNA treatment comments",
		"index_well": "SMRTbell barcoded adapter plate 3.0 Index well",
		"barcode": "Barcode",
		"shear_femtol_id": "Shearing Femto ID",
		"shear_av_size": "Shearing Av. size (bp)",
		"seq_femto_id": "Library Femto ID",
		"seq_av_size": "Library Av. size (bp)",
		"library_conc": "Library Conc. (ng/uL)",
		"comment": "Comments"
	},
	"HiC_Library": {
		"hic_library_tube_id": "Library Tube ID",
		"lysate_id": "Lysate Tube ID",
		"hic_num": "#",
		"hic_status": "Status",
		"library_method": "Library Prep Method",
		"library_date": "Library Prep Date",
		"library_id": "Library Batch ID",
		"prox_ligation_conc": "Proximity Ligation Conc. (ng/ul)",
		"purified_dna_total": "Total Purified DNA",
		"index_set": "Dovetail® Dual Index Primer Set #1 For Illumina®",
		"library_conc": "Library Conc. (ng/uL)",
		"library_size": "Library size (bp)",
		"hic_comments": "Comments"
	},
	"Sequencing": {
		"sequencing_id": "Sequencing ID",
		"rna_library_tube_id": "Library Tube ID",
		"illumina_library_tube_id": "Library Tube ID",
		"ont_library_tube_id": "Library Tube ID",
		"pacbio_library_tube_id": "Library Tube ID",
		"hic_library_tube_id": "Library Tube ID",
		"technology": "Technology",
		"instrument": "Sequencing Instrument",
		"run_date": "Sequencing Date",
		"run_id": "Sequencing Run ID",
		"cell_id": "SMRTcell well / Flowcell",
		"smrt_num": "No. SMRTcells",
		"seq_comments": "Comments",
        "seq_type": "Type"
	}
}

excel_to_db_cols = {
	"Sample": {
        "Specimen ID": "og_id",
		"Field Identifier": "field_id",
		"Nominal Species ID": "nominal_species_id",
		"Common name/s": "common_name",
		"Collector": "collector",
		"Contact": "contact",
		"Date_Collected": "date_collected",
		"Sex": "sex",
		"Weight (g)": "weight",
		"Length (TL or FL mm)": "lengthTL_and_lengthFL",
		"Country": "country",
		"State": "state",
		"Location": "location",
		"Latitude_Collection": "latitude_collection",
		"Longitude_Collection": "longitude_collection",
		"Depth_Collection (m)": "depth_collection",
		"Collection_Method": "collection_method",
		"Preservation_Method": "preservation_method",
		"Sample_Condition": "sample_condition",
		"Photo_Voucher": "photo_voucher",
		"Photo_Voucher_Accession_Details": "photo_id",
		"Specimen_Voucher": "specimen_voucher",
		"Specimen_Voucher_Accession_details": "voucher_id",
		"Comments": "comments",
		"Priority": "priority",
		"Tissues": "tissues",
		"Extracted": "extracted",
		"DNA Extraction Status": "extraction_queue",
		"ilmn": "ilmn",
		"Illumina Status": "il_status",
		"hifi": "hifi",
		"PacBio Status": "pb_status",
		"hic": "hic",
		"HiC Status": "hic_status",
		"nano": "nano",
		"NanoPore Status": "ont_num",
		"rna": "rna",
		"RNA Extraction Status": "rna_status",
		"ilrna": "ilrna",
		"Illumina RNA Status": "ilrna_status"
	},
	"Tissue": {
		"Sample ID": "tissue_id",
		"Specimen ID": "og_id",
		"Field Identifier": "field_id",
		"Alt ID": "alt_id",
		"Tissue": "tissue",
		"Extracted": "extracted",
		"Freezer": "freezer",
		"Shelf": "shelf",
		"Rack": "rack",
		"Level": "level",
		"Box Label": "box",
		"Comment": "comment"
	},
	"RNA_Extraction": {
		"Tube ID": "rna_id",
		"Sample ID": "tissue_id",
		"#": "ext_num",
		"Status": "status",
		"Extraction Method": "extraction_method",
		"Extraction Date": "extraction_date",
		"Extraction Batch ID": "extraction_batch_id",
		"Final Buffer": "final_buffer",
		"Volume (uL)": "volume",
		"Qubit Conc. (ng/uL)": "qubit_conc",
		"NanoDrop Conc. (ng/uL)": "nano_drop_conc",
		"260/280": "ratio_260_280",
		"260/230": "ratio_260_230",
		"Total Yield (ng)": "total_yield",
		"TapeStation Run ID": "tapestation_id",
		"RNA DV200": "rna_dv200",
		"RIN": "rin",
		"Pass / Fail QC": "extraction_qc",
		"Comment": "comment",
		"RNA Archives Freezer": "rna_freezer",
		"Shelf": "rna_shelf",
		"Rack": "rna_rack",
		"Level": "rna_level",
		"Box Label": "rna_box",
		"Notes": "rna_notes"
	},
	"DNA_Extraction": {
		"Tube ID": "dna_id",
		"Sample ID": "tissue_id",
		"#": "ext_num",
		"Status": "status",
		"Extraction Method": "extraction_method",
		"Extraction Date": "extraction_date",
		"Extraction Batch ID": "extraction_batch_id",
		"Final Buffer": "final_buffer",
		"Volume (uL)": "volume",
		"Qubit Conc. (ng/uL)": "qubit_conc",
		"NanoDrop Conc. (ng/uL)": "nano_drop_conc",
		"260/280": "ratio_260_280",
		"260/230": "ratio_260_230",
		"Qubit:NanoDrop Ratio": "ratioqubit_nanodrop",
		"Total Yield (ng)": "total_yield",
		"gDNA Femto ID": "gdna_femtol_id",
		"Average size (bp)": "av_size",
		"Pass / Fail QC": "extraction_qc",
		"Comment": "comment",
		"DNA Archives Freezer": "dna_Freezer",
		"Shelf": "dna_Shelf",
		"Rack": "dna_Rack",
		"Level": "dna_Level",
		"Box Label": "dna_Box",
		"Notes": "dna_Notes"
	},
	"HiC_Lysate": {
		"Lysate Tube ID": "lysate_id",
		"Sample ID": "tissue_id",
		"#": "lysate_num",
		"Status": "lysate_status",
		"Lysate Prep Date": "lysate_prep_date",
		"Lysate Batch ID": "lysate_batch_id",
		"Lysate Conc. (ng/uL)": "lysate_conc",
		"Total Lysate (ng)": "total_lysate",
		"CDE (%)": "lysate_cde",
		"Comments": "lysate_comments"
	},
	"RNA_Library": {
		"Library Tube ID": "rna_library_tube_id",
		"RNA Tube ID": "rna_id",
		"#": "rna_num",
		"Status": "rna_status",
		"Library Prep Method": "library_method",
		"Library Prep Date": "library_date",
		"Library Batch ID": "library_id",
		"cDNA Library Size (bp)": "library_size",
		"% Product": "perc_product",
		"Library Qubit Conc. (ng/ul)": "library_qubit_conc",
		"Library Molarity (nM)": "library_molarity",
		"IDT® for Illumina® DNA/RNA UD Indexes Set": "index_set",
		"Illumina Index Adaptor Well": "index_well",
		"Illumina Contatenate Index": "index_inx",
		"PacBo Kinnex Barcoded Primers": "kinnex_primers",
		"PacBio Kinnex Library Barcode": "kinnex_barcode",
		"Comments": "il_comments"
	},
	"Illumina_Library": {
		"Library Tube ID": "illumina_library_tube_id",
		"DNA Tube ID": "dna_id",
		"#": "ilmn_num",
		"Status": "ilmn_status",
		"Library Prep Method": "library_method",
		"Library Prep Date": "library_date",
		"Library Batch ID": "library_id",
		"IDT® for Illumina® DNA/RNA UD Indexes Set": "index_set",
		"Index Adaptor Well": "index_well",
		"Concatenate Index": "index_idx",
		"Library Qubit Conc. (ng/ul)": "library_qubit_conc",
		"Comments": "il_comments"
	},
	"ONT_Library": {
		"Library Tube ID": "ont_library_tube_id",
		"DNA Tube ID": "dna_id",
		"#": "ont_num",
		"Status": "ont_status",
		"Library Prep Date": "library_date",
		"Library Batch ID": "library_id",
		"Library Prep Method": "library_method",
		"Library Type": "library_type",
		"Estimated Loading size (bp)": "est_loading_size",
		"Comments": "ont_comments"
	},
	"PacBio_Library": {
		"Library Tube ID": "pacbio_library_tube_id",
		"DNA Tube ID": "dna_id",
		"#": "pacb_num",
		"Status": "pacb_status",
		"Library Prep Method": "library_method",
		"Library Prep Date": "library_date",
		"Library Batch ID": "library_id",
		"DNA treatment comments": "dna_treatment",
		"SMRTbell barcoded adapter plate 3.0 Index well": "index_well",
		"Barcode": "barcode",
		"Shearing Femto ID": "shear_femtol_id",
		"Shearing Av. size (bp)": "shear_av_size",
		"Library Femto ID": "seq_femto_id",
		"Library Av. size (bp)": "seq_av_size",
		"Library Conc. (ng/uL)": "library_conc",
		"Comments": "comment"
	},
	"HiC_Library": {
		"Library Tube ID": "hic_library_tube_id",
		"Lysate Tube ID": "lysate_id",
		"#": "hic_num",
		"Status": "hic_status",
		"Library Prep Method": "library_method",
		"Library Prep Date": "library_date",
		"Library Batch ID": "library_id",
		"Proximity Ligation Conc. (ng/ul)": "prox_ligation_conc",
		"Total Purified DNA": "purified_dna_total",
		"Dovetail® Dual Index Primer Set #1 For Illumina®": "index_set",
		"Library Conc. (ng/uL)": "library_conc",
		"Library size (bp)": "library_size",
		"Comments": "hic_comments"
	},
	"Sequencing": {
		"Specimen ID": "og_id",
        "Sequencing ID": "sequencing_id",
		"Technology": "technology",
		"Sequencing Instrument": "instrument",
		"Sequencing Date": "run_date",
		"Sequencing Run ID": "run_id",
		"SMRTcell well / Flowcell": "cell_id",
		"No. SMRTcells": "smrt_num",
		"Comments": "seq_comments",
        "Type": "seq_type"
	}
}
