tables = [
    "Sample",
    "Tissue",
    "RNA_Extraction",
    "DNA_Extraction",
    "HiC_Lysate",
    "RNA_Library",
    "Illumina_Library",
    "ONT_Library",
    "PacBio_Library",
    "HiC_Library",
    "Sequencing",
    #"Mito_Genome_Sequencing",
    #"Reference_Genome_Sequencing",
    #"Draft_Genome_Sequencing",
    "Mito_Genome",
    "Reference_Genome",
    "Draft_Genome",
    "LCA"
]

primary_keys = {
    "Sample": "og_id",
    "Tissue": "tissue_id",
    "RNA_Extraction": "rna_id",
    "DNA_Extraction": "dna_id",
    "HiC_Lysate": "lysate_id",
    "RNA_Library": "rna_library_tube_id",
    "Illumina_Library": "illumina_library_tube_id",
    "ONT_Library": "ont_library_tube_id",
    "PacBio_Library": "pacbio_library_tube_id",
    "HiC_Library": "hic_library_tube_id",
    "Sequencing": "sequencing_id",
    #"Mito_Genome_Sequencing": ["mito_id", "sequencing_id"],
    #"Reference_Genome_Sequencing": ["ref_id", "sequencing_id"],
    #"Draft_Genome_Sequencing": ["draft_id", "sequencing_id"],
    "Mito_Genome": "mito_id",
    "Reference_Genome": "ref_id",
    "Draft_Genome": "draft_id",
    "LCA": "lca_id"
}

one_to_many_conn = {
    "Sample": ["Tissue"],
    "Tissue": ["RNA_Extraction", "DNA_Extraction", "HiC_Lysate"],
    "RNA_Extraction": ["RNA_Library"],
    "DNA_Extraction": ["Illumina_Library", "ONT_Library", "PacBio_Library"],
    "HiC_Lysate": ["HiC_Library"],
    "RNA_Library": ["Sequencing"],
    "Illumina_Library": ["Sequencing"],
    "ONT_Library": ["Sequencing"],
    "PacBio_Library": ["Sequencing"],
    "HiC_Library": ["Sequencing"],
    #"Sequencing": ["Mito_Genome_Sequencing", "Reference_Genome_Sequencing", "Draft_Genome_Sequencing"],
    "Sequencing": ["Mito_Genome", "Reference_Genome", "Draft_Genome"],
    "Mito_Genome": ["LCA", "Mito_Genome_Sequencing"],
    "Reference_Genome": ["Reference_Genome_Sequencing"],
    "Draft_Genome": ["Draft_Genome_Sequencing"],
}

many_to_one_conn = {
    "LCA": ["Mito_Genome"],
    #"Mito_Genome_Sequencing": ["Mito_Genome", "Sequencing"],
    #"Reference_Genome_Sequencing": ["Reference_Genome", "Sequencing"],
    #"Draft_Genome_Sequencing": ["Draft_Genome", "Sequencing"],
    "Mito_Genome": ["Sequencing"],
    "Reference_Genome": ["Sequencing"],
    "Draft_Genome": ["Sequencing"],
    "Sequencing": ["RNA_Library", "Illumina_Library", "ONT_Library", "PacBio_Library", "HiC_Library"],
    "RNA_Library": ["RNA_Extraction"],
    "Illumina_Library": ["DNA_Extraction"],
    "ONT_Library": ["DNA_Extraction"],
    "PacBio_Library": ["DNA_Extraction"],
    "HiC_Library": ["HiC_Lysate"],
    "RNA_Extraction": ["Tissue"],
    "DNA_Extraction": ["Tissue"],
    "HiC_Lysate": ["Tissue"],
    "Tissue": ["Sample"],
}
